# Step 1: Use a node base image
FROM node:latest as build-step

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY AuthServer/package.json /app
RUN npm install

# Copy the rest of your app's source code
COPY ./AuthServer /app

# Build your Angular app
RUN npm run build:prod

# Step 2: Use Nginx to serve the app
FROM nginx:alpine

# Copy the build output to replace the default nginx contents.
COPY --from=build-step /app/dist/Hyyak /usr/share/nginx/html
COPY --from=build-step /app/nginx.conf /etc/nginx/conf.d/default.conf
COPY AuthServer/dynamic-env.json /usr/share/nginx/html

# Expose port 80
EXPOSE 3300

# Start Nginx and keep it running
CMD ["nginx", "-g", "daemon off;"]